[theme]
# Primary colors
primaryColor = "#002855"     
backgroundColor = "#FFFFFF"    
secondaryBackgroundColor = "#f8f9fa" 
textColor = "#002855"         

base = "light"

[client]
toolbarMode = "minimal"
showErrorDetails = false

[server]
headless = true
fileWatcherType = "auto"
runOnSave = true  

[runner]
magicEnabled = true
fastReruns = true

[browser]
gatherUsageStats = false

[ui]
hideTopBar = true